spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tGNYf3AAywKoqdj2v4d
      secret-key: AmSvYpQQhKZP982ysETGaMSCWC4Gua
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
      sms:
        host: https://fesms.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 1
        appcode: e3875e7094db4b398b632f963df0c20e

  application:
    name: mall-third-party
server:
  port: 30000